### ISSUE TITLE
BUG - running curl command prints error

### ISSUE THREAD

**Issue by open-schnick** [FileFighter/ClientSetup#19]
/home/..../FileFighter/ClientSetup-master/Install.sh: line 43: printUsage: command not found

**Comment by qvalentin** [comment]
finished unpacking FileFighter. Installing it now...

/home/ffsys/FileFighter/ClientSetup-master/Install.sh: line 4: ./lib/utils.sh: No such file or directory
/home/ffsys/FileFighter/ClientSetup-master/Install.sh: line 19: echoLogo: command not found
Creating Install Location under /home/ffsys/filefighter
Copying Scripts to new location...
Copying FileFighter Application to /usr/bin...
This may need administrator rights (sudo) if you are not root.
[sudo] password for ffsys: 

Successfully installed FileFighter!
You can delete the downloaded files (/home/ffsys/FileFighter/ClientSetup-master/) if you want.

/home/ffsys/FileFighter/ClientSetup-master/Install.sh: line 43: printUsage: command not found

**Comment by open-schnick** [comment]
hmmm...

**Comment by open-schnick** [comment]
should be fixed in #20
